---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "seaweedfs-csi-driver.name" . }}-controller-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "seaweedfs-csi-driver.name" . }}-node-sa
