kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: seaweedfs-storage
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.isDefaultStorageClass }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
provisioner: seaweedfs-csi-driver
