
# host and port of your SeaweedFs filer
seaweedfsFiler: ""
storageClassName: seaweedfs-storage
isDefaultStorageClass: false
tlsSecret: ""

imagePullPolicy: "IfNotPresent"

csiProvisioner:
  image: quay.io/k8scsi/csi-provisioner:v1.6.1
  resources: {}

csiAttacher:
  image: quay.io/k8scsi/csi-attacher:v1.2.1
  resources: {}

csiNodeDriverRegistrar:
  image: quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
  resources: {}

seaweedfsCsiPlugin:
  image: chrislusf/seaweedfs-csi-driver:latest
  resources: {}

# NOT Change, for future releases. Must be equal Name in GetPluginInfoResponse
driverName: seaweedfs-csi-driver

node:
  # Deploy node daemonset
  enabled: true
  # When pod on node be recreated all pod on same node lost PV.
  # For safe update use updateStrategy.type: OnDelete and manual move pods who use PV and delete damonset pod
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%


