
# host and port of your SeaweedFs filer
seaweedfsFiler: "SEAWEEDFS_FILER"
storageClassName: seaweedfs-storage
isDefaultStorageClass: false
tlsSecret: ""
#logVerbosity: 4

imagePullPolicy: "IfNotPresent"

#imagePullSecrets:
#- name: mycredentials

csiProvisioner:
  image: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
  resources: {}

csiAttacher:
  image: k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
  resources: {}

csiResizer:
  image: k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
  resources: {}

csiNodeDriverRegistrar:
  image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
  resources: {}

seaweedfsCsiPlugin:
  image: chrislusf/seaweedfs-csi-driver:latest
  resources: {}

# NOT Change, for future releases. Must be equal Name in GetPluginInfoResponse
driverName: seaweedfs-csi-driver

controller:
  #affinity:
  #tolerations:

node:
  # Deploy node daemonset
  enabled: true
  # When pod on node be recreated all pod on same node lost PV.
  # For safe update use updateStrategy.type: OnDelete and manual move pods who use PV and delete damonset pod
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
  #affinity:
  #tolerations:
