apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-csi-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # This value is enforced after 2022/03/18
  storageClassName: seaweedfs-storage
